name: musique
version: "1"
summary: The perfect™ music player
description: |
  Musique is a music player built for speed, simplicity and style. It is
  written in C++ using the Qt framework. Contributing is welcome, especially
  in the Linux desktop integration area.
confinement: devmode
grade: devel

apps:
  musique:
    command: desktop-launch $SNAP/usr/local/bin/musique
    plugs: [x11, home, unity7, network, network-bind, pulseaudio]

parts:
  musique:
    plugin: qmake
    qt-version: qt4
    source: .
    build-packages:
      - build-essential
      - fakeroot
      - qt4-dev-tools
      - qt4-qmake
      - libtag1-dev
      - libphonon-dev
      - libqt4-sql-sqlite
    stage-packages:
      - fontconfig-config
      - libqt4-sql-sqlite
      - libqtcore4
      - phonon
      - phonon-backend-gstreamer
    after: [desktop-qt4]
